"""
Nombres y descripciones de las 43 clases del dataset GTSRB.
"""

CLASS_NAMES = {
    0:  "Limite velocidad 20 km/h",
    1:  "Limite velocidad 30 km/h",
    2:  "Limite velocidad 50 km/h",
    3:  "Limite velocidad 60 km/h",
    4:  "Limite velocidad 70 km/h",
    5:  "Limite velocidad 80 km/h",
    6:  "Fin limite velocidad 80 km/h",
    7:  "Limite velocidad 100 km/h",
    8:  "Limite velocidad 120 km/h",
    9:  "Prohibido adelantar",
    10: "Prohibido adelantar vehiculos >3.5t",
    11: "Prioridad en interseccion",
    12: "Carretera con prioridad",
    13: "Ceda el paso",
    14: "STOP",
    15: "Prohibido el paso",
    16: "Prohibido paso vehiculos >3.5t",
    17: "Prohibido entrar",
    18: "Precaucion general",
    19: "Curva peligrosa a la izquierda",
    20: "Curva peligrosa a la derecha",
    21: "Curva doble",
    22: "Pavimento irregular",
    23: "Pavimento deslizante",
    24: "Calzada se estrecha por la derecha",
    25: "Obras en la via",
    26: "Semaforos",
    27: "Peatones",
    28: "Ninos cruzando",
    29: "Ciclistas",
    30: "Peligro hielo o nieve",
    31: "Animales salvajes",
    32: "Fin de limites de velocidad y adelantamiento",
    33: "Gire a la derecha",
    34: "Gire a la izquierda",
    35: "Siga recto",
    36: "Siga recto o gire a la derecha",
    37: "Siga recto o gire a la izquierda",
    38: "Mantenga la derecha",
    39: "Mantenga la izquierda",
    40: "Rotonda obligatoria",
    41: "Fin prohibicion de adelantar",
    42: "Fin prohibicion adelantar >3.5t",
}

DESCRIPTIONS = {
    0:  "Velocidad maxima permitida: 20 km/h. Zona residencial o escolar.",
    1:  "Velocidad maxima permitida: 30 km/h. Zona urbana de baja velocidad.",
    2:  "Velocidad maxima permitida: 50 km/h. Velocidad tipica en ciudad.",
    3:  "Velocidad maxima permitida: 60 km/h.",
    4:  "Velocidad maxima permitida: 70 km/h.",
    5:  "Velocidad maxima permitida: 80 km/h. Fuera de poblado.",
    6:  "Fin del limite de 80 km/h. Recupera velocidad permitida anterior.",
    7:  "Velocidad maxima permitida: 100 km/h. Via rapida o autopista.",
    8:  "Velocidad maxima permitida: 120 km/h. Autopista.",
    9:  "Prohibido adelantar a todos los vehiculos.",
    10: "Prohibido adelantar a vehiculos de mas de 3.5 toneladas.",
    11: "Tienes prioridad en la proxima interseccion.",
    12: "Esta carretera tiene prioridad sobre las vias secundarias.",
    13: "Ceda el paso a los vehiculos que circulan por la via principal.",
    14: "Detencion obligatoria. Para completamente antes de continuar.",
    15: "Prohibido el paso para todos los vehiculos.",
    16: "Prohibido el paso a vehiculos de mas de 3.5 toneladas.",
    17: "Prohibido entrar. Via de sentido contrario.",
    18: "Peligro generico adelante. Extrema precaucion.",
    19: "Curva peligrosa hacia la izquierda. Reduce velocidad.",
    20: "Curva peligrosa hacia la derecha. Reduce velocidad.",
    21: "Doble curva peligrosa. Reduce velocidad considerablemente.",
    22: "Pavimento en mal estado. Reduce velocidad.",
    23: "Pavimento resbaladizo. Evita frenadas bruscas.",
    24: "La calzada se estrecha por el lado derecho.",
    25: "Obras en la carretera. Reduce velocidad y atento a obreros.",
    26: "Semaforos proximos. Preparate para detenerte.",
    27: "Zona de peatones. Reduce velocidad y cede el paso.",
    28: "Zona escolar. Ninos cruzando. Reduce velocidad.",
    29: "Cruce de ciclistas. Precaucion al adelantar.",
    30: "Peligro de hielo o nieve en la calzada.",
    31: "Posible presencia de animales salvajes en la via.",
    32: "Fin de todas las restricciones de velocidad y adelantamiento.",
    33: "Obligatorio girar a la derecha en la proxima interseccion.",
    34: "Obligatorio girar a la izquierda en la proxima interseccion.",
    35: "Obligatorio seguir recto.",
    36: "Obligatorio seguir recto o girar a la derecha.",
    37: "Obligatorio seguir recto o girar a la izquierda.",
    38: "Mantenga su vehiculo por el lado derecho.",
    39: "Mantenga su vehiculo por el lado izquierdo.",
    40: "Rotonda obligatoria. Ceda el paso a los vehiculos dentro.",
    41: "Fin de la prohibicion de adelantar.",
    42: "Fin de la prohibicion de adelantar para vehiculos >3.5t.",
}
